/**
 * The only notification types that exist. Notifications are generated by
 * the backend from domain events; no client can create one, so no client
 * can invent a type.
 */
export enum NotificationType {
  RIDE_REQUEST = "RIDE_REQUEST",
  RIDE_DRIVER_ASSIGNED = "RIDE_DRIVER_ASSIGNED",
  RIDE_DRIVER_ACCEPTED = "RIDE_DRIVER_ACCEPTED",
  RIDE_DRIVER_ARRIVING = "RIDE_DRIVER_ARRIVING",
  RIDE_DRIVER_ARRIVED = "RIDE_DRIVER_ARRIVED",
  RIDE_STARTED = "RIDE_STARTED",
  RIDE_COMPLETED = "RIDE_COMPLETED",
  RIDE_CANCELLED = "RIDE_CANCELLED",
  RIDE_NO_DRIVER = "RIDE_NO_DRIVER",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  RATING_REMINDER = "RATING_REMINDER",
  SOS_CREATED = "SOS_CREATED",
  SOS_UPDATED = "SOS_UPDATED",
  DRIVER_APPROVED = "DRIVER_APPROVED",
  DRIVER_REJECTED = "DRIVER_REJECTED",
  COMPLAINT_CREATED = "COMPLAINT_CREATED",
  COMPLAINT_UPDATED = "COMPLAINT_UPDATED",
  GENERAL = "GENERAL",
}

/** Push delivery outcome, recorded on the in-app notification. */
export enum PushStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
  /** The user has no active device token (never logged in on a phone, logged out). */
  NO_DEVICES = "NO_DEVICES",
  /** FCM is not configured on this server. In-app notification only. */
  SKIPPED = "SKIPPED",
}

/**
 * High priority wakes the device and shows a heads-up banner. Reserved for
 * things the user must act on now: a ride offer, the driver at the door,
 * a safety alert.
 */
const HIGH_PRIORITY: ReadonlySet<NotificationType> = new Set([
  NotificationType.RIDE_REQUEST,
  NotificationType.RIDE_DRIVER_ASSIGNED,
  NotificationType.RIDE_DRIVER_ARRIVING,
  NotificationType.RIDE_DRIVER_ARRIVED,
  NotificationType.RIDE_CANCELLED,
  NotificationType.SOS_CREATED,
  NotificationType.SOS_UPDATED,
]);

export const isHighPriority = (type: NotificationType): boolean => HIGH_PRIORITY.has(type);

/** Ride notifications replace each other in the tray instead of piling up. */
const RIDE_TYPES: ReadonlySet<NotificationType> = new Set([
  NotificationType.RIDE_DRIVER_ASSIGNED,
  NotificationType.RIDE_DRIVER_ACCEPTED,
  NotificationType.RIDE_DRIVER_ARRIVING,
  NotificationType.RIDE_DRIVER_ARRIVED,
  NotificationType.RIDE_STARTED,
  NotificationType.RIDE_COMPLETED,
  NotificationType.RIDE_CANCELLED,
  NotificationType.RIDE_NO_DRIVER,
]);

export const isRideStatusType = (type: NotificationType): boolean => RIDE_TYPES.has(type);
