/**
 * The only notification types that exist. Notifications are generated by
 * the backend from domain events; no client can create one, so no client
 * can invent a type.
 */
export enum NotificationType {
  RIDE_REQUEST = "RIDE_REQUEST",
  RIDE_DRIVER_ASSIGNED = "RIDE_DRIVER_ASSIGNED",
  RIDE_DRIVER_ACCEPTED = "RIDE_DRIVER_ACCEPTED",
  RIDE_DRIVER_ARRIVING = "RIDE_DRIVER_ARRIVING",
  RIDE_DRIVER_ARRIVED = "RIDE_DRIVER_ARRIVED",
  RIDE_STARTED = "RIDE_STARTED",
  RIDE_COMPLETED = "RIDE_COMPLETED",
  RIDE_CANCELLED = "RIDE_CANCELLED",
  RIDE_NO_DRIVER = "RIDE_NO_DRIVER",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  /** A refund is on its way to the customer. */
  REFUND_INITIATED = "REFUND_INITIATED",
  /** Razorpay processed the refund (the bank may take a few days to show it). */
  REFUND_PROCESSED = "REFUND_PROCESSED",
  /** A refund reduced the driver's earnings. */
  EARNING_ADJUSTED = "EARNING_ADJUSTED",
  RATING_REMINDER = "RATING_REMINDER",
  SOS_CREATED = "SOS_CREATED",
  SOS_UPDATED = "SOS_UPDATED",
  DRIVER_APPROVED = "DRIVER_APPROVED",
  DRIVER_REJECTED = "DRIVER_REJECTED",
  DRIVER_SUSPENDED = "DRIVER_SUSPENDED",
  DRIVER_REINSTATED = "DRIVER_REINSTATED",
  /** A change to verified driver/vehicle details or documents was approved. */
  DRIVER_UPDATE_APPROVED = "DRIVER_UPDATE_APPROVED",
  DRIVER_UPDATE_REJECTED = "DRIVER_UPDATE_REJECTED",
  COMPLAINT_CREATED = "COMPLAINT_CREATED",
  COMPLAINT_UPDATED = "COMPLAINT_UPDATED",
  GENERAL = "GENERAL",
  /** Admin broadcast (Phase 7): service announcements, maintenance, offers. */
  ANNOUNCEMENT = "ANNOUNCEMENT",
}

/** Push delivery outcome, recorded on the in-app notification. */
export enum PushStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
  /** The user has no active device token (never logged in on a phone, logged out). */
  NO_DEVICES = "NO_DEVICES",
  /** FCM is not configured on this server. In-app notification only. */
  SKIPPED = "SKIPPED",
}

/**
 * High priority wakes the device and shows a heads-up banner. Reserved for
 * things the user must act on now: a ride offer, the driver at the door,
 * a safety alert.
 */
const HIGH_PRIORITY: ReadonlySet<NotificationType> = new Set([
  NotificationType.RIDE_REQUEST,
  NotificationType.RIDE_DRIVER_ASSIGNED,
  NotificationType.RIDE_DRIVER_ARRIVING,
  NotificationType.RIDE_DRIVER_ARRIVED,
  NotificationType.RIDE_CANCELLED,
  NotificationType.SOS_CREATED,
  NotificationType.SOS_UPDATED,
]);

export const isHighPriority = (type: NotificationType): boolean => HIGH_PRIORITY.has(type);

/** Ride notifications replace each other in the tray instead of piling up. */
const RIDE_TYPES: ReadonlySet<NotificationType> = new Set([
  NotificationType.RIDE_DRIVER_ASSIGNED,
  NotificationType.RIDE_DRIVER_ACCEPTED,
  NotificationType.RIDE_DRIVER_ARRIVING,
  NotificationType.RIDE_DRIVER_ARRIVED,
  NotificationType.RIDE_STARTED,
  NotificationType.RIDE_COMPLETED,
  NotificationType.RIDE_CANCELLED,
  NotificationType.RIDE_NO_DRIVER,
]);

export const isRideStatusType = (type: NotificationType): boolean => RIDE_TYPES.has(type);

/**
 * The alert sound a push plays. Android takes the sound from the
 * notification channel (a channel's sound cannot change once it exists on a
 * phone), so each sound has its own channel, created by the app at start-up
 * (MainActivity.kt and push_notifications.dart). The files ship inside the
 * app: res/raw/<sound>.wav on Android, <sound>.wav in the iOS bundle.
 */
export enum PushSound {
  /** A new ride offer for a driver: loud, repeating, hard to miss. */
  RIDE_REQUEST = "ride_request",
  /** Ride progress and payments: a short friendly chime. */
  RIDE_UPDATE = "ride_update",
  /** Safety alerts: a siren. */
  SOS_ALERT = "sos_alert",
}

/** Android channel id per sound. Keep in sync with the app. */
export const PUSH_CHANNEL_IDS: Record<PushSound, string> = {
  [PushSound.RIDE_REQUEST]: "tirvona_ride_requests",
  [PushSound.RIDE_UPDATE]: "tirvona_rides_v2",
  [PushSound.SOS_ALERT]: "tirvona_sos",
};

export function pushSoundFor(type: NotificationType): PushSound {
  switch (type) {
    case NotificationType.RIDE_REQUEST:
      return PushSound.RIDE_REQUEST;
    case NotificationType.SOS_CREATED:
    case NotificationType.SOS_UPDATED:
      return PushSound.SOS_ALERT;
    default:
      return PushSound.RIDE_UPDATE;
  }
}
