// Stable, machine-readable codes surfaced in ApiErrorBody.code so client apps
// (Flutter, admin) can branch on failure type instead of parsing `message`.
export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_BLOCKED: "USER_BLOCKED",

  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",

  DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
  DRIVER_NOT_APPROVED: "DRIVER_NOT_APPROVED",
  DRIVER_ALREADY_SUBMITTED: "DRIVER_ALREADY_SUBMITTED",
  DRIVER_KYC_INCOMPLETE: "DRIVER_KYC_INCOMPLETE",
  INVALID_DRIVER_STATUS: "INVALID_DRIVER_STATUS",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",

  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_INVALID_TYPE: "DOCUMENT_INVALID_TYPE",
  DOCUMENT_TOO_LARGE: "DOCUMENT_TOO_LARGE",
  DOCUMENT_NOT_EDITABLE: "DOCUMENT_NOT_EDITABLE",

  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  VEHICLE_ALREADY_EXISTS: "VEHICLE_ALREADY_EXISTS",

  DRIVER_OFFLINE: "DRIVER_OFFLINE",
  DRIVER_NO_ACTIVE_VEHICLE: "DRIVER_NO_ACTIVE_VEHICLE",
  DRIVER_LOCATION_REQUIRED: "DRIVER_LOCATION_REQUIRED",
  DRIVER_HAS_ACTIVE_RIDE: "DRIVER_HAS_ACTIVE_RIDE",

  RIDE_TYPE_NOT_FOUND: "RIDE_TYPE_NOT_FOUND",
  RIDE_TYPE_INACTIVE: "RIDE_TYPE_INACTIVE",
  PRICING_NOT_CONFIGURED: "PRICING_NOT_CONFIGURED",

  RIDE_NOT_FOUND: "RIDE_NOT_FOUND",
  RIDE_ALREADY_ACTIVE: "RIDE_ALREADY_ACTIVE",
  RIDE_TOO_SHORT: "RIDE_TOO_SHORT",
  RIDE_TOO_LONG: "RIDE_TOO_LONG",
  RIDE_STATE_CONFLICT: "RIDE_STATE_CONFLICT",
  RIDE_NOT_CANCELLABLE: "RIDE_NOT_CANCELLABLE",
  RIDE_OTP_INVALID: "RIDE_OTP_INVALID",
  RIDE_OTP_EXPIRED: "RIDE_OTP_EXPIRED",
  RIDE_OTP_TOO_MANY_ATTEMPTS: "RIDE_OTP_TOO_MANY_ATTEMPTS",

  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_RIDE_NOT_COMPLETED: "PAYMENT_RIDE_NOT_COMPLETED",
  PAYMENT_FARE_UNAVAILABLE: "PAYMENT_FARE_UNAVAILABLE",
  PAYMENT_ALREADY_COMPLETED: "PAYMENT_ALREADY_COMPLETED",
  PAYMENT_NOT_PAYABLE: "PAYMENT_NOT_PAYABLE",
  PAYMENT_IN_PROGRESS: "PAYMENT_IN_PROGRESS",
  PAYMENT_ORDER_MISMATCH: "PAYMENT_ORDER_MISMATCH",
  PAYMENT_SIGNATURE_INVALID: "PAYMENT_SIGNATURE_INVALID",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_ID_REUSED: "PAYMENT_ID_REUSED",
  PAYMENT_NOT_CAPTURED: "PAYMENT_NOT_CAPTURED",
  PAYMENT_GATEWAY_NOT_CONFIGURED: "PAYMENT_GATEWAY_NOT_CONFIGURED",
  PAYMENT_GATEWAY_ERROR: "PAYMENT_GATEWAY_ERROR",
  PAYMENT_WEBHOOK_INVALID: "PAYMENT_WEBHOOK_INVALID",

  EARNING_NOT_FOUND: "EARNING_NOT_FOUND",
  EARNING_NOT_AVAILABLE: "EARNING_NOT_AVAILABLE",
  COMMISSION_NOT_CONFIGURED: "COMMISSION_NOT_CONFIGURED",
  COMMISSION_NOT_CANCELLABLE: "COMMISSION_NOT_CANCELLABLE",

  RATING_NOT_ALLOWED: "RATING_NOT_ALLOWED",
  RATING_ALREADY_EXISTS: "RATING_ALREADY_EXISTS",
  RATING_WINDOW_CLOSED: "RATING_WINDOW_CLOSED",

  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  EMERGENCY_CONTACT_NOT_FOUND: "EMERGENCY_CONTACT_NOT_FOUND",
  EMERGENCY_CONTACT_LIMIT: "EMERGENCY_CONTACT_LIMIT",
  EMERGENCY_CONTACT_DUPLICATE: "EMERGENCY_CONTACT_DUPLICATE",
  EMERGENCY_CONTACT_SELF: "EMERGENCY_CONTACT_SELF",

  SOS_NOT_ALLOWED: "SOS_NOT_ALLOWED",
  SOS_NOT_FOUND: "SOS_NOT_FOUND",
  SOS_INVALID_TRANSITION: "SOS_INVALID_TRANSITION",

  SHARE_NOT_ALLOWED: "SHARE_NOT_ALLOWED",
  SHARE_LINK_NOT_FOUND: "SHARE_LINK_NOT_FOUND",
  SHARE_LINK_EXPIRED: "SHARE_LINK_EXPIRED",

  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",
  COMPLAINT_NOT_ALLOWED: "COMPLAINT_NOT_ALLOWED",
  COMPLAINT_ALREADY_OPEN: "COMPLAINT_ALREADY_OPEN",
  COMPLAINT_INVALID_TRANSITION: "COMPLAINT_INVALID_TRANSITION",

  ADMIN_UNAUTHORIZED: "ADMIN_UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
