// Stable, machine-readable codes surfaced in ApiErrorBody.code so client apps
// (Flutter, admin) can branch on failure type instead of parsing `message`.
export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_BLOCKED: "USER_BLOCKED",

  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",
  // The code was replaced by a newer one, already used, or never existed.
  OTP_NOT_ACTIVE: "OTP_NOT_ACTIVE",
  OTP_RESEND_TOO_SOON: "OTP_RESEND_TOO_SOON",
  OTP_SEND_LIMIT_REACHED: "OTP_SEND_LIMIT_REACHED",
  OTP_DELIVERY_FAILED: "OTP_DELIVERY_FAILED",
  WHATSAPP_RECIPIENT_UNAVAILABLE: "WHATSAPP_RECIPIENT_UNAVAILABLE",

  // Signup (WhatsApp OTP)
  PHONE_INVALID: "PHONE_INVALID",
  PHONE_ALREADY_REGISTERED: "PHONE_ALREADY_REGISTERED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  SIGNUP_SESSION_INVALID: "SIGNUP_SESSION_INVALID",
  PHONE_ALREADY_VERIFIED: "PHONE_ALREADY_VERIFIED",

  DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
  DRIVER_NOT_APPROVED: "DRIVER_NOT_APPROVED",
  DRIVER_ALREADY_SUBMITTED: "DRIVER_ALREADY_SUBMITTED",
  DRIVER_KYC_INCOMPLETE: "DRIVER_KYC_INCOMPLETE",
  INVALID_DRIVER_STATUS: "INVALID_DRIVER_STATUS",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",

  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_INVALID_TYPE: "DOCUMENT_INVALID_TYPE",
  DOCUMENT_TOO_LARGE: "DOCUMENT_TOO_LARGE",
  DOCUMENT_NOT_EDITABLE: "DOCUMENT_NOT_EDITABLE",

  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  VEHICLE_ALREADY_EXISTS: "VEHICLE_ALREADY_EXISTS",
  DRIVER_VEHICLE_LIMIT: "DRIVER_VEHICLE_LIMIT",

  DRIVER_OFFLINE: "DRIVER_OFFLINE",
  DRIVER_NO_ACTIVE_VEHICLE: "DRIVER_NO_ACTIVE_VEHICLE",
  DRIVER_LOCATION_REQUIRED: "DRIVER_LOCATION_REQUIRED",
  DRIVER_HAS_ACTIVE_RIDE: "DRIVER_HAS_ACTIVE_RIDE",

  RIDE_TYPE_NOT_FOUND: "RIDE_TYPE_NOT_FOUND",
  RIDE_TYPE_INACTIVE: "RIDE_TYPE_INACTIVE",
  PRICING_NOT_CONFIGURED: "PRICING_NOT_CONFIGURED",

  RIDE_NOT_FOUND: "RIDE_NOT_FOUND",
  RIDE_ALREADY_ACTIVE: "RIDE_ALREADY_ACTIVE",
  RIDE_TOO_SHORT: "RIDE_TOO_SHORT",
  RIDE_TOO_LONG: "RIDE_TOO_LONG",
  RIDE_STATE_CONFLICT: "RIDE_STATE_CONFLICT",
  RIDE_NOT_CANCELLABLE: "RIDE_NOT_CANCELLABLE",
  RIDE_OTP_INVALID: "RIDE_OTP_INVALID",
  RIDE_OTP_EXPIRED: "RIDE_OTP_EXPIRED",
  RIDE_OTP_TOO_MANY_ATTEMPTS: "RIDE_OTP_TOO_MANY_ATTEMPTS",
  RIDE_HISTORY_RANGE_INVALID: "RIDE_HISTORY_RANGE_INVALID",

  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_RIDE_NOT_COMPLETED: "PAYMENT_RIDE_NOT_COMPLETED",
  PAYMENT_FARE_UNAVAILABLE: "PAYMENT_FARE_UNAVAILABLE",
  PAYMENT_ALREADY_COMPLETED: "PAYMENT_ALREADY_COMPLETED",
  PAYMENT_NOT_PAYABLE: "PAYMENT_NOT_PAYABLE",
  PAYMENT_IN_PROGRESS: "PAYMENT_IN_PROGRESS",
  PAYMENT_ORDER_MISMATCH: "PAYMENT_ORDER_MISMATCH",
  PAYMENT_SIGNATURE_INVALID: "PAYMENT_SIGNATURE_INVALID",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_ID_REUSED: "PAYMENT_ID_REUSED",
  PAYMENT_NOT_CAPTURED: "PAYMENT_NOT_CAPTURED",
  PAYMENT_GATEWAY_NOT_CONFIGURED: "PAYMENT_GATEWAY_NOT_CONFIGURED",
  PAYMENT_GATEWAY_ERROR: "PAYMENT_GATEWAY_ERROR",
  PAYMENT_WEBHOOK_INVALID: "PAYMENT_WEBHOOK_INVALID",

  REFUND_NOT_FOUND: "REFUND_NOT_FOUND",
  REFUND_NOT_ALLOWED: "REFUND_NOT_ALLOWED",
  REFUND_NOT_SUPPORTED: "REFUND_NOT_SUPPORTED",
  REFUND_WINDOW_EXPIRED: "REFUND_WINDOW_EXPIRED",
  REFUND_TARGET_INVALID: "REFUND_TARGET_INVALID",
  REFUND_AMOUNT_INVALID: "REFUND_AMOUNT_INVALID",
  REFUND_NOTHING_LEFT: "REFUND_NOTHING_LEFT",
  REFUND_IN_PROGRESS: "REFUND_IN_PROGRESS",
  REFUND_REJECTED: "REFUND_REJECTED",
  REFUND_IDEMPOTENCY_CONFLICT: "REFUND_IDEMPOTENCY_CONFLICT",
  REFUND_ALREADY_REVIEWED: "REFUND_ALREADY_REVIEWED",
  RECONCILIATION_RUNNING: "RECONCILIATION_RUNNING",
  RECONCILIATION_RUN_NOT_FOUND: "RECONCILIATION_RUN_NOT_FOUND",
  RECONCILIATION_EXCEPTION_NOT_FOUND: "RECONCILIATION_EXCEPTION_NOT_FOUND",

  EARNING_NOT_FOUND: "EARNING_NOT_FOUND",
  EARNING_NOT_AVAILABLE: "EARNING_NOT_AVAILABLE",
  ADJUSTMENT_NOT_FOUND: "ADJUSTMENT_NOT_FOUND",
  ADJUSTMENT_NOT_OUTSTANDING: "ADJUSTMENT_NOT_OUTSTANDING",
  COMMISSION_NOT_CONFIGURED: "COMMISSION_NOT_CONFIGURED",
  COMMISSION_NOT_CANCELLABLE: "COMMISSION_NOT_CANCELLABLE",

  RATING_NOT_ALLOWED: "RATING_NOT_ALLOWED",
  RATING_ALREADY_EXISTS: "RATING_ALREADY_EXISTS",
  RATING_WINDOW_CLOSED: "RATING_WINDOW_CLOSED",

  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  EMERGENCY_CONTACT_NOT_FOUND: "EMERGENCY_CONTACT_NOT_FOUND",
  EMERGENCY_CONTACT_LIMIT: "EMERGENCY_CONTACT_LIMIT",
  EMERGENCY_CONTACT_DUPLICATE: "EMERGENCY_CONTACT_DUPLICATE",
  EMERGENCY_CONTACT_SELF: "EMERGENCY_CONTACT_SELF",

  SOS_NOT_ALLOWED: "SOS_NOT_ALLOWED",
  SOS_NOT_FOUND: "SOS_NOT_FOUND",
  SOS_INVALID_TRANSITION: "SOS_INVALID_TRANSITION",

  SHARE_NOT_ALLOWED: "SHARE_NOT_ALLOWED",
  SHARE_LINK_NOT_FOUND: "SHARE_LINK_NOT_FOUND",
  SHARE_LINK_EXPIRED: "SHARE_LINK_EXPIRED",

  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",
  COMPLAINT_NOT_ALLOWED: "COMPLAINT_NOT_ALLOWED",
  COMPLAINT_ALREADY_OPEN: "COMPLAINT_ALREADY_OPEN",
  COMPLAINT_INVALID_TRANSITION: "COMPLAINT_INVALID_TRANSITION",

  PLACE_NOT_FOUND: "PLACE_NOT_FOUND",
  PLACES_UNAVAILABLE: "PLACES_UNAVAILABLE",

  // ── Phase 7 ───────────────────────────────────────────────────────────
  RIDE_TYPE_ALREADY_EXISTS: "RIDE_TYPE_ALREADY_EXISTS",
  RIDE_TYPE_PRICING_REQUIRED: "RIDE_TYPE_PRICING_REQUIRED",

  ZONE_NOT_FOUND: "ZONE_NOT_FOUND",
  ZONE_ALREADY_EXISTS: "ZONE_ALREADY_EXISTS",
  ZONE_INVALID_BOUNDARY: "ZONE_INVALID_BOUNDARY",
  SERVICE_AREA_UNAVAILABLE: "SERVICE_AREA_UNAVAILABLE",

  PROMO_NOT_FOUND: "PROMO_NOT_FOUND",
  PROMO_ALREADY_EXISTS: "PROMO_ALREADY_EXISTS",
  PROMO_INVALID: "PROMO_INVALID",
  PROMO_INACTIVE: "PROMO_INACTIVE",
  PROMO_NOT_STARTED: "PROMO_NOT_STARTED",
  PROMO_EXPIRED: "PROMO_EXPIRED",
  PROMO_RIDE_TYPE_NOT_ELIGIBLE: "PROMO_RIDE_TYPE_NOT_ELIGIBLE",
  PROMO_MIN_FARE_NOT_MET: "PROMO_MIN_FARE_NOT_MET",
  PROMO_USAGE_LIMIT_REACHED: "PROMO_USAGE_LIMIT_REACHED",
  PROMO_USER_LIMIT_REACHED: "PROMO_USER_LIMIT_REACHED",

  CANCELLATION_REASON_NOT_FOUND: "CANCELLATION_REASON_NOT_FOUND",
  CANCELLATION_REASON_EXISTS: "CANCELLATION_REASON_EXISTS",
  CANCELLATION_REASON_INVALID: "CANCELLATION_REASON_INVALID",
  CANCELLATION_NOT_FOUND: "CANCELLATION_NOT_FOUND",
  CANCELLATION_FEE_NOT_DUE: "CANCELLATION_FEE_NOT_DUE",

  BROADCAST_NOT_FOUND: "BROADCAST_NOT_FOUND",
  BROADCAST_NOT_EDITABLE: "BROADCAST_NOT_EDITABLE",
  BROADCAST_INVALID_SCHEDULE: "BROADCAST_INVALID_SCHEDULE",

  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  REPORT_RANGE_INVALID: "REPORT_RANGE_INVALID",

  ADMIN_UNAUTHORIZED: "ADMIN_UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // ── Branding ──────────────────────────────────────────────────────────
  BRANDING_NOT_SET: "BRANDING_NOT_SET",
  BRANDING_INVALID_IMAGE: "BRANDING_INVALID_IMAGE",

  // ── Popular places ────────────────────────────────────────────────────
  POPULAR_PLACE_NOT_FOUND: "POPULAR_PLACE_NOT_FOUND",
  POPULAR_PLACE_INVALID_IMAGE: "POPULAR_PLACE_INVALID_IMAGE",
  POPULAR_PLACE_IMAGE_NOT_SET: "POPULAR_PLACE_IMAGE_NOT_SET",

  // ── Account: password reset, profile photo, saved places ──────────────
  // No account uses this number (forgot password).
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  // The one-time token from a verified reset code is expired, used or unknown.
  PASSWORD_RESET_INVALID: "PASSWORD_RESET_INVALID",
  // The new password is the one the account already has.
  PASSWORD_UNCHANGED: "PASSWORD_UNCHANGED",
  PROFILE_IMAGE_INVALID: "PROFILE_IMAGE_INVALID",
  PROFILE_IMAGE_NOT_SET: "PROFILE_IMAGE_NOT_SET",
  SAVED_PLACE_NOT_FOUND: "SAVED_PLACE_NOT_FOUND",
  SAVED_PLACE_LIMIT_REACHED: "SAVED_PLACE_LIMIT_REACHED",
  SAVED_PLACE_DUPLICATE_LABEL: "SAVED_PLACE_DUPLICATE_LABEL",

  // ── Driver changes after approval ─────────────────────────────────────
  DRIVER_CHANGE_NOT_FOUND: "DRIVER_CHANGE_NOT_FOUND",
  // Already approved, rejected or withdrawn.
  DRIVER_CHANGE_NOT_PENDING: "DRIVER_CHANGE_NOT_PENDING",
  // The request would change nothing.
  DRIVER_CHANGE_EMPTY: "DRIVER_CHANGE_EMPTY",
  // An approved driver tried to edit verified details directly.
  DRIVER_CHANGE_REVIEW_REQUIRED: "DRIVER_CHANGE_REVIEW_REQUIRED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
