export interface AuthenticationCodeMessage {
  /** Recipient in E.164 (+919876543210). */
  to: string;
  /** The one-time code, already generated by OtpService. */
  code: string;
}

export interface WhatsAppSendResult {
  /** Meta's message id (wamid.…); "log-…" for the development gateway. */
  messageId: string;
}

/**
 * Why a message was not accepted, reduced to what the caller can act on.
 * Meta's own codes and messages stay in the server log, never in API
 * responses.
 */
export type WhatsAppFailureReason =
  /** The number cannot receive WhatsApp messages (not on WhatsApp, not allow-listed on a test sender). */
  | "RECIPIENT_UNAVAILABLE"
  /** Meta throttled us (throughput, per-recipient pair rate, spam limits). */
  | "RATE_LIMITED"
  /** Our side is wrong: token, template name/parameters, phone number id. Needs an operator. */
  | "MISCONFIGURED"
  /** Meta unreachable, timed out or failed internally. Retrying later may work. */
  | "UNAVAILABLE";

export class WhatsAppDeliveryError extends Error {
  constructor(
    readonly reason: WhatsAppFailureReason,
    message: string,
  ) {
    super(message);
    this.name = "WhatsAppDeliveryError";
  }
}

/**
 * The only door to WhatsApp. AuthService/OtpService decide *when* a code is
 * sent; implementations decide *how* it is delivered — Meta specifics never
 * leak past this boundary. Production binds the Meta Cloud API gateway,
 * local development a log-only gateway, and the e2e suites a fake.
 */
export abstract class WhatsAppGateway {
  /** Human-readable name for logs and the health/diagnostics output. */
  abstract readonly provider: string;

  /**
   * Sends the signup authentication template. Resolves only once Meta has
   * accepted the message; otherwise throws [WhatsAppDeliveryError].
   */
  abstract sendAuthenticationCode(message: AuthenticationCodeMessage): Promise<WhatsAppSendResult>;
}
